#! /bin/sh
# make and install all 3 libraires
# run with sudo or as root
# it will install directories in /usr/local/lib
# You may need to run ldconfig (use sudo or be root) after the libraries are installed
# You may need to edit /etc/ls.so.conf and add /usr/local/lib.

# GDSL (Generic C Data Structures)
./gdsl-1.4/configure
./gdsl-1.4/make
./gdsl-1.4/make install

# Expat, needed for SCEW
./expat-2.0.0/configure
./expat-2.0.0/make
./expat-2.0.0/make install

# SCEW, wrapper funtions for expat xml parsing, etc.
./scew-0.4.0/configure
./scew-0.4.0/make
./scew-0.4.0/make install
